spreadsheet_url = "https://docs.google.com/spreadsheets/d/1YlqAupxgc4dKiuBH79IOzJYWX32moKbVne9bYQAd-QM/edit#gid=0"

[gcp_service_account]
type = "service_account"
project_id = "streamlit-badminton"
private_key_id = "26404a2bf5b18aaa0b792cb12c680d7587db9049"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDOun0ZTLW9CNjB
Drtn0/sf/+48w7T/OQSBPyvcgojoZJ0rlWiJef+O1h7kRVCmclBAOG8HZDo6aCW2
fsT80avL/U1xQ1Zdudg0L17dSAbFTHeLNNire8+Q60Z/m7AwjpxtdgVA/5he7tI5
7KBTkbfR3c+GV2h0bO2sFM/4NtG0Y8/kEOIkQVkAVD3mvohoTeZ8g1qnSdGOlOfX
pJGVoG/GM3DDKOybQ+UUEkuehK1vfdmufC5uwTT7JBHaOFPN3DkK3c9pw2/UjYVH
x1Zv/ONgvYbxeq8kk9jixev5iMIYqBgv8CJnuB1uedELNp+DoW7PAomplFJTcjYh
mDKOdldJAgMBAAECggEALdxXs8TdfWvov/1fbENtzrXFWXQWI1d4DR8hQRgxPJLT
fi91QyhOHhcYv82zvFUYQgLy+JoOw9XGZgOd+jMecFDHfRSx5HV9xefrXN4laGAU
Fgz5cyNykuTq3RTCA6ejgrH/rOF24TqMZx68G4X0WEmjh9s8uDVRDY+Janho0aI7
Xz154KW3TeZ6R+rs/xAWzfrXqPrMI9if2k64EZxb7hjJhl76G5/gzQ25vwydMVUv
dH3DFSKqoQ+miPj2rHdz7oeZdYwtpGqOj9iCLALKQ9h2RVFlp4+Z5jNnPr+/RZBq
PgPLdOvJTWmq2W3+gchWKAMic8Y8gCWoJb1LComk7QKBgQD8ttW9qMufQOlRaOz6
4S6Y1oio8if+HA62/Z1cWae5W+2qrMMQerC6cLC7xT/3ioYyE/IaAJMHz5O6Y5+c
Hldp1qF1oukh8ik7Aa1HxH3/a0Psw/7l7KyuYFPJSByrlXukKg4SCziXNJttmj9b
Wsj6MVTkyVa/2ZrmIuNlu1MoXQKBgQDRapbUjo3hX2wMKnnIRMlehkcVowFdAPt+
GqTvUMAY64wqG4xY4QOjxAEKycMz9e0ZFJlzTOIpdavli57kGDJiGH08nppCmsxN
OZOnfGqohTJ/pogv39p/ajvXgzSYePCmkX0FLkbmx/L5/SxbF/mtwKW1M0StNiX2
dsJqP6qL3QKBgGjUp2GfjagoUyD0N6nyk1PPWq1KlpBwryH1nrtabZsUqUhtlhVV
783HRWj+8AQNsJFBeOKUbmmFEDD3dpRaecRrxlp4E+GDBNt3XJwyxFmZ83lZ7HkQ
bql/SAJtKYd74Og+kcumX/lJV1hl7fZFeK1gnWiypIu9BuaEfnQK+vn5AoGAM0Ku
DPWgESy0W/4BtV3xFKw1tjwiV0uoQ+Ptv466lt8BfkUkA5WAuJN/1c4xdASctujt
7uVA7vkYzKVyjU7G9nAcJ7yC8g7GN5kCZZr02K9R/yEacO2QpGOypjw9oZzo+zzd
p2j+ffsvpLWuJ9Ykjb18UnBsPSHmBQBo8m0HKBkCgYBiqKwldEz6z3+uj+SNniay
jqMHjIf9b0FvwQbtUI81ituA9e0xpY0i77U1xXnH4xWIhpu+ytSNQfBgUjqD/mrZ
8LGJ6LI2tJzYtTIVG+KKKPW2OtkSd1kGBXoq5w61D4dapNXsxRCFtalOTLWqlQqc
BapFD6wQykSaUECC/dkNUA==
-----END PRIVATE KEY-----"""
client_email = "badminton@streamlit-badminton.iam.gserviceaccount.com"
client_id = "115918370315226724362"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/badminton%40streamlit-badminton.iam.gserviceaccount.com"
